controller_manager:
        ros__parameters:
                update_rate: 30
                use_sim_time: true

                diff_drive_controller:
                        type: diff_drive_controller/DiffDriveController

                joint_trajectory_controller:
                        type: joint_trajectory_controller/JointTrajectoryController

                joint_state_broadcaster:
                        type: joint_state_broadcaster/JointStateBroadcaster


joint_trajectory_controller:
        ros__parameters:
                joints:
                        - front_left_steer_joint
                        - front_right_steer_joint
    
                interface_name: position
        
                command_interfaces:
                        - position
        
                state_interfaces:
                        - position
                        - velocity

diff_drive_controller:
        ros__parameters:
                publish_rate: 50.0

                base_frame_id: base_footprint

                left_wheel_names: ['wheel_left_joint']
                right_wheel_names: ['wheel_right_joint']
                wheel_separation: 1.6
                wheel_radius: 0.31265

                use_stamped_vel: false
